version: "3.8"
services:

  postgres-book:
    image: "postgres:13"
    container_name: "postgres-book"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=bookdb
    volumes:
      - postgres-book-data:/var/lib/postgresql/data

volumes:
  postgres-book-data:
    name: postgres-book-data