server:
  port: 8001

spring:
  application:
    name: book-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
  datasource:
    url: jdbc:postgresql://localhost:5432/bookdb
    username: admin
    password: admin
  profiles:
    active: test-data
